export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const SET_MESSAGE = 'SET_MESSAGE';
// export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
// export const SIGNUP = 'SIGNUP';
// export const LOADAPP = 'LOADAPP';
export const LOG_OUT = 'LOG_OUT';
// export const AUTH_LOADING = 'AUTH_LOADING';
// export const AUTH_FAILED = 'AUTH_FAILED';